apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-rag-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: financial-rag
  template:
    metadata:
      labels:
        app: financial-rag
    spec:
      containers:
      - name: financial-rag
        image: bindu2009/financial-rag:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
